import {
    ErButton,
    ErButtonGroup,
    ErIcon,
    ErCollapse,
    ErCollapseItem,
    ErAlert,
    ErTooltip,
    ErPopconfirm,
    ErDropdown,
    ErDropdownItem,
    ErMessage,
    ErNotification,
    ErInput,
    ErMessageBox,
    ErForm,
    ErFormItem,
    ErLoading,
    ErSwitch,
    ErSelect,
    ErOption
} from '@zznikki-element/components';
import type { Plugin } from 'vue'

export default [
    ErButton,
    ErIcon,
    ErButtonGroup,
    ErCollapse,
    ErCollapseItem,
    ErAlert,
    ErTooltip,
    ErPopconfirm,
    ErDropdown,
    ErDropdownItem,
    ErMessage,
    ErNotification,
    ErMessageBox,
    ErInput,
    ErForm,
    ErFormItem,
    ErLoading,
    ErSwitch,
    ErSelect,
    ErOption
] as Plugin[]